### ISSUE TITLE
Accessibility issues

### ISSUE THREAD

**Issue by GeeLaw** [shifuchen/Key-Expediter#2]
# Contrast
The contrast of unselected ingredients against the white background is too low.

![The contrast is too low](https://cloud.githubusercontent.com/assets/4462444/15973984/b62a21aa-2f78-11e6-8223-34df2aa5799c.png)

It's recommended to have the contrast increased. Moreover, it might be better to have some of them selected at first.

# High contrast theme failure
The site fails to indicate the selection when high contrast theme is applied. The following is an example for High Contrast Black. It actually fails every high contrast theme.

![The UI fails to indicate selection when High Contrast Black is applied](https://cloud.githubusercontent.com/assets/4462444/15974073/30d3d284-2f79-11e6-8731-e100b4cebb59.png)

It's recommended that the UI use more than one visual to indicate the selection.

**Comment by shifuchen** [comment]
I've just added **opacity** as an additional dimension indicating the mode of the selection. This makes it more accessible for visitors using high-contrast themes. The unselected items possess lower opacities, which, when working with high-contrast themes, would be displayed in gray instead of white.

For the advice of having some of them being selected at first, I don't know what it's intended for. If you click the _Expedite!_ button when nothing is selected, the four selections would be lit up automatically and a password containing all of them would be generated.

Feel free to leave a comment if you have any further concerns!

**Comment by GeeLaw** [comment]
The issue is well addressed :-)
